[package]
name = "tttdb"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tttdb"
path = "src/bin/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ttt = { path = "../ttt" }
